version: "3.8"

# default network: bridge
networks:
    default:
        driver: bridge

services:    
    nginx:
        image: nginx:42 # 42 is the tag of the image
        build: 
            context: ./requirements/nginx
            dockerfile: Dockerfile
        container_name: nginx
        ports:
            - "443:443"
        volumes:
            - 
    mariadb:
        container_name: mariadb
        image: 
        build:
            context: ./requirements/mariadb
            dockerfile: Dockerfile



    wordpress:
