version: "3.8"

# default network: bridge
networks:
    default:
        driver: bridge

services:    
    nginx:
        depends_on:
            - wordpress
        image: nginx:eahn # eahn is the tag of the image
        build: 
            context: ./requirements/nginx
            dockerfile: Dockerfile
        container_name: nginx
        ports:
            - "443:443"
        volumes:
            - wordpress:/var/www/html
        networks:
            - default
        env_file:
            - .env
        restart: always

    wordpress:
        depends_on:
            - mariadb
        image: wordpress:eahn
        build:
            context: ./requirements/wordpress
            dockerfile: Dockerfile
        container_name: wordpress
        volumes:
            - wordpress:/var/www/html
        networks:
            - default
        env_file:
            - .env
        restart: always

    mariadb:
        container_name: mariadb
        image: mariadb:eahn
        build:
            context: ./requirements/mariadb
            dockerfile: Dockerfile
        volumes:
            - mariadb:/var/lib/mysql
        networks:
            - default
        env_file:
            - .env
        restart: always

volumes:
    wordpress:
        driver: local
        driver_opts:
            device: /Users/eunsu/data/wordpress # Should create folders and change path when using it at school (mkdir -p ..)
            type: none
            o: bind
    mariadb:
        driver: local
        driver_opts:
            device: /Users/eunsu/data/mariadb # Should create folders and change path when using it at school (mkdir -p ..) -p means parent
            type: none
            o: bind
