
networks:
  inception:
    name: inception
    driver: bridge

services:
  mariadb:
    container_name: mariadb
    image: mariadb:eahn
    build:
      context: ./requirements/mariadb/
    env_file:
      - .env
    networks:
      - inception
    volumes:
      - database:/var/lib/mysql
    restart: always

  wordpress:
    depends_on:
      - mariadb
    container_name: wordpress
    image: wordpress:eahn
    build:
      context: ./requirements/wordpress/
    env_file:
      - .env
    networks:
      - inception
    volumes:
     - wordpress:/var/www/wordpress
    restart: always


  nginx:
    depends_on:
      - wordpress
    container_name: nginx
    image: nginx:eahn
    build:
      context: ./requirements/nginx/
    env_file:
      - .env
    ports:
      - "443:443"
    networks:
      - inception
    volumes:
      - wordpress:/var/www/wordpress
    restart: always

volumes:
  database:
    name: database
    driver: local
    driver_opts:
      o: "bind"
      type: none
      device: ~/data/database
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      o: "bind"
      type: none
      device: ~/data/wordpress
