# version: "3.8"

# default network: bridge
networks:
  inception:
    name: inception
    driver: bridge

services:    
    nginx:
        container_name: nginx
        depends_on:
            - wordpress
        image: nginx:eahn # eahn is the tag of the image
        build: 
            context: ./requirements/nginx
            dockerfile: Dockerfile
        environment:
            PATH_SSL_CERTS: /etc/nginx/ssl/server.crt
        ports:
            - "443:443"
        volumes:
            - wp:/var/www/html
        env_file:
            - .env
        networks:
            - inception

    wordpress:
        container_name: wordpress
        depends_on:
            - mariadb
        image: wordpress:eahn
        build:
            context: ./requirements/wordpress
            dockerfile: Dockerfile
        volumes:
            - wp:/var/www/html
        env_file:
            - .env
        networks:
            - inception

    mariadb:
        container_name: mariadb
        image: mariadb:eahn
        build:
            context: ./requirements/mariadb
            dockerfile: Dockerfile
        volumes:
            - db:/var/lib/mysql
        env_file:
            - .env
        networks:
            - inception

volumes:
    wp:
        driver_opts:
            device: /Users/eunsu/data/wp # Should create folders (data/wp) and change path when using it at school (mkdir -p ..)
            type: none
            o: "bind"
    db:
        driver_opts:
            device: /Users/eunsu/data/db # Should create folders (data/db) and change path when using it at school (mkdir -p ..) -p means parent
            type: none
            o: "bind"
